apiVersion: v1
kind: Service 
metadata:
  name: multi-container-service
  #it should be same as the name of the service in the pod yaml file
  labels:
    app: multi-container-app
    environment: production
    team: DevOps
namespace: Project
spec:
  #The selector is used to identify the pods that this service will route traffic to. It should match the labels defined in the pod specification.
  selector:
    app: multi-container-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  
  