apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
  namespace: default
spec:
  - containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: emptydir-volume #this name should be equal to volume name mention below
          mountPath: /var/log/nginx/

      #This SideCar Container used to read the nginx logs
      - name: almalinux
        image: almalinux:9
        command: ["sleep","10000"]
        volumeMounts:
        - name: emptydir-volume
          mountPath: /mnt/nginx-log 
          readOnly: true
    volumes:
      - name: emptydir-volume #this is the name of the volume
        emptyDir:
          sizeLimit: 100Mi