#Write Deployment and Service for ROBOSHOP Project
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend
  #it should be same as the name of the deployment in the pod yaml file
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata: 
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: prasanthkumar30/frontend:v1
          imagePullPolicy: Always # always pull the image from docker hub for every deployment
          ports:
            - name: liveness-port
              containerPort: 80
          livenessProbe:
              httpGet:
                path: /
                port: liveness-port
              failureThreshold: 1
              periodSeconds: 15
          readinessProbe:
              httpGet:
                path: /
                port: liveness-port
              failureThreshold: 1
              periodSeconds: 15
          volumeMounts:
            - name: frontend-config # this name refers to the volume name defined in the volumes section below
              mountPath: /etc/nginx/nginx.conf # this is the path where the config file will be mounted inside the container
              subPath: nginx.conf # this is the file name in the config map which will be mounted to the above path
      volumes:
        - name: frontend-config # this name should be same as the volumeMounts name
          configMap:
            name: nginx-config # this is the name of the config map which contains the nginx.conf fil
            namespace: roboshop     
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #Container port